FROM public.ecr.aws/lambda/python:3.11

# Copy requirements
COPY requirements.txt /tmp/requirements.txt

# Install dependencies to /tmp/python
RUN pip install -r /tmp/requirements.txt -t /tmp/python

# The compiled dependencies are now in /tmp/python
